export const professors = [
  { id:"001", name:"Clayton Greenberg", username:"Greenberg", password:"password590", assigned:[] },
  { id:"002", name:"Harry Smith", username:"Smith", password:"password590", assigned:[] },
  { id:"003", name:"Stephanie Weirich", username:"Weirich", password:"password590", assigned:[] },
  { id:"004", name:"Rajiv Gandhi", username:"Gandhi", password:"password590", assigned:[] },
  { id:"005", name:"Val Breazu Tannen", username:"Tannen", password:"password590", assigned:[] },
  { id:"006", name:"Swapneel Sheth", username:"Sheth", password:"password590", assigned:[] },
  { id:"007", name:"Thomas Joseph Farmer", username:"Farmer", password:"password590", assigned:[] },
  { id:"008", name:"Anindya De", username:"De", password:"password590", assigned:[] },
  { id:"009", name:"Sanjeev Khanna", username:"Khanna", password:"password590", assigned:[] },
  { id:"010", name:"Max Mintz", username:"Mintz", password:"password590", assigned:[] },
  { id:"011", name:"Dinesh Jayaraman", username:"Jayaraman", password:"password590", assigned:[] },
  { id:"012", name:"Mayur H Naik", username:"Naik", password:"password590", assigned:[] },
  { id:"013", name:"Zachary Ives", username:"Ives", password:"password590", assigned:[] },
  { id:"014", name:"Adam D Mally", username:"Mally", password:"password590", assigned:[] },
  { id:"015", name:"Joseph L Devietti", username:"Devietti", password:"password590", assigned:[] },
  { id:"016", name:"Jocelyn Alys Quaintance", username:"Quaintance", password:"password590", assigned:[] },
  { id:"017", name:"Shivani Agarwal", username:"Agarwal", password:"password590", assigned:[] },
  { id:"018", name:"Lyle H Ungar", username:"Ungar", password:"password590", assigned:[] },
  { id:"019", name:"Mark Yatskar", username:"Yatskar", password:"password590", assigned:[] },
  { id:"020", name:"Ophir Shalem", username:"Shalem", password:"password590", assigned:[] },
  { id:"021", name:"Susan B Davidson", username:"Davidson", password:"password590", assigned:[] },
  { id:"022", name:"Boon Thau Loo", username:"Loo", password:"password590", assigned:[] },
  { id:"023", name:"Vincent F Liu", username:"Liu", password:"password590", assigned:[] },
  { id:"024", name:"Eric Noel Fouh Mbindi", username:"Mbindi", password:"password590", assigned:[] },
  { id:"025", name:"Stephen Lane", username:"Lane", password:"password590", assigned:[] },
  { id:"026", name:"Konstantinos Daniilidis", username:"Daniilidis", password:"password590", assigned:[] },
  { id:"027", name:"Dan Roth", username:"Roth", password:"password590", assigned:[] },
  { id:"028", name:"Stephan A. Zdancewic", username:"Zdancewic", password:"password590", assigned:[] },
  { id:"029", name:"Brandon L Krakowsky", username:"Krakowsky", password:"password590", assigned:[] },
  { id:"030", name:"Insup Lee", username:"Lee", password:"password590", assigned:[] },
  { id:"031", name:"Arvind Bhusnurmath", username:"Bhusnurmath", password:"password590", assigned:[] },
  { id:"032", name:"Jean Henri Gallier", username:"Gallier", password:"password590", assigned:[] }
];

export const courses = {
  "CIT590": { id:"CIT590", name:"Programming Languages and Techniques", lecturer:"Brandon L Krakowsky", days:"MW", start:"16:30", end:"18:00", capacity:110, enrolled:[] },
  "CIT591": { id:"CIT591", name:"Introduction to Software Development", lecturer:"Arvind Bhusnurmath", days:"MW", start:"12:00", end:"13:30", capacity:120, enrolled:[] },
  "CIT592": { id:"CIT592", name:"Mathematical Foundations of Computer Science", lecturer:"Clayton Greenberg", days:"TR", start:"10:00", end:"11:00", capacity:72, enrolled:[] },
  "CIT593": { id:"CIT593", name:"Introduction to Computer Systems", lecturer:"Thomas Joseph Farmer", days:"MWF", start:"11:00", end:"12:00", capacity:72, enrolled:[] },
  "CIT594": { id:"CIT594", name:"Data Structures and Software Design", lecturer:"Eric Noel Fouh Mbindi", days:"TR", start:"10:30", end:"12:00", capacity:72, enrolled:[] },
  "CIT595": { id:"CIT595", name:"Computer Systems Programming", lecturer:"Insup Lee", days:"TR", start:"15:00", end:"16:30", capacity:72, enrolled:[] },
  "CIT596": { id:"CIT596", name:"Algorithms and Computation", lecturer:"Arvind Bhusnurmath", days:"MW", start:"10:30", end:"12:00", capacity:120, enrolled:[] },
  "CIS105": { id:"CIS105", name:"Computational Data Exploration", lecturer:"Clayton Greenberg", days:"MWF", start:"10:00", end:"11:00", capacity:60, enrolled:[] },
  "CIS110": { id:"CIS110", name:"Introduction to Computer Programming", lecturer:"Harry Smith", days:"MWF", start:"9:00", end:"10:00", capacity:375, enrolled:[] },
  "CIS120": { id:"CIS120", name:"Programming Languages and Techniques", lecturer:"Stephanie Weirich", days:"MWF", start:"11:00", end:"12:00", capacity:300, enrolled:[] },
  "CIS160": { id:"CIS160", name:"Mathematical Foundations of Computer Science", lecturer:"Val Breazu Tannen", days:"TR", start:"13:30", end:"14:30", capacity:100, enrolled:[] },
  "CIS121": { id:"CIS121", name:"Programming Languages and Techniques II", lecturer:"Rajiv Gandhi", days:"TR", start:"9:00", end:"10:30", capacity:125, enrolled:[] },
  "CIS191": { id:"CIS191", name:"Linux/Unix Skills", lecturer:"Swapneel Sheth", days:"F", start:"13:30", end:"15:00", capacity:15, enrolled:[] },
  "CIS192": { id:"CIS192", name:"Python Programming", lecturer:"Swapneel Sheth", days:"MW", start:"10:30", end:"12:00", capacity:30, enrolled:[] },
  "CIS195": { id:"CIS195", name:"Mobile App Development", lecturer:"Swapneel Sheth", days:"MW", start:"13:00", end:"14:30", capacity:45, enrolled:[] },
  "CIS196": { id:"CIS196", name:"Ruby on Rails Web Development", lecturer:"Swapneel Sheth", days:"TR", start:"15:00", end:"16:30", capacity:15, enrolled:[] },
  "CIS197": { id:"CIS197", name:"Javascript", lecturer:"Swapneel Sheth", days:"TR", start:"10:30", end:"12:00", capacity:25, enrolled:[] },
  "CIS198": { id:"CIS198", name:"Rust Programming", lecturer:"Swapneel Sheth", days:"TR", start:"12:00", end:"13:30", capacity:15, enrolled:[] },
  "CIS240": { id:"CIS240", name:"Introduction to Computer Systems", lecturer:"Thomas Joseph Farmer", days:"TR", start:"10:30", end:"12:00", capacity:200, enrolled:[] },
  "CIS262": { id:"CIS262", name:"Automata Computability and Complexity", lecturer:"Anindya De", days:"TR", start:"9:00", end:"10:30", capacity:150, enrolled:[] },
  "CIS320": { id:"CIS320", name:"Introduction to Algorithms", lecturer:"Sanjeev Khanna", days:"MW", start:"15:00", end:"16:30", capacity:200, enrolled:[] },
  "CIS398": { id:"CIS398", name:"Quantum Computer and Information Science", lecturer:"Max Mintz", days:"TR", start:"16:00", end:"18:00", capacity:15, enrolled:[] },
  "CIS419": { id:"CIS419", name:"Applied Machine Learning", lecturer:"Dinesh Jayaraman", days:"TR", start:"13:30", end:"15:00", capacity:120, enrolled:[] },
  "CIS450": { id:"CIS450", name:"Database and Information Systems", lecturer:"Mayur H Naik", days:"MW", start:"10:30", end:"12:00", capacity:200, enrolled:[] },
  "CIS455": { id:"CIS455", name:"Internet and Web Systems", lecturer:"Zachary Ives", days:"MW", start:"15:00", end:"16:30", capacity:100, enrolled:[] },
  "CIS460": { id:"CIS460", name:"Interactive Computer Graphics", lecturer:"Adam D Mally", days:"MW", start:"12:00", end:"13:30", capacity:80, enrolled:[] },
  "CIS461": { id:"CIS461", name:"Advanced Rendering", lecturer:"Adam D Mally", days:"MW", start:"13:30", end:"15:00", capacity:50, enrolled:[] },
  "CIS471": { id:"CIS471", name:"Computer Organization and Design", lecturer:"Joseph L Devietti", days:"TR", start:"12:00", end:"13:30", capacity:170, enrolled:[] },
  "CIS511": { id:"CIS511", name:"Theory of Computation", lecturer:"Jean Henri Gallier", days:"MW", start:"15:00", end:"16:30", capacity:125, enrolled:[] },
  "CIS515": { id:"CIS515", name:"Fundamentals of Linear Algebra and Optimization", lecturer:"Jocelyn Alys Quaintance", days:"TR", start:"13:30", end:"15:00", capacity:500, enrolled:[] },
  "CIS519": { id:"CIS519", name:"Applied Machine Learning", lecturer:"Dinesh Jayaraman", days:"TR", start:"13:30", end:"15:00", capacity:120, enrolled:[] },
  "CIS520": { id:"CIS520", name:"Machine Learning", lecturer:"Shivani Agarwal", days:"TR", start:"13:00", end:"15:00", capacity:125, enrolled:[] },
  "CIS522": { id:"CIS522", name:"Deep Learning for Data Science", lecturer:"Lyle H Ungar", days:"TR", start:"15:00", end:"16:30", capacity:125, enrolled:[] },
  "CIS530": { id:"CIS530", name:"Computational Linguistics", lecturer:"Mark Yatskar", days:"TR", start:"16:30", end:"18:00", capacity:75, enrolled:[] },
  "CIS535": { id:"CIS535", name:"Introduction to Bioinformatics", lecturer:"Ophir Shalem", days:"MWF", start:"10:00", end:"11:00", capacity:43, enrolled:[] },
  "CIS545": { id:"CIS545", name:"Big Data Analytics", lecturer:"Susan B Davidson", days:"TR", start:"10:30", end:"12:00", capacity:300, enrolled:[] },
  "CIS548": { id:"CIS548", name:"Operating Systems Design and Implementation", lecturer:"Boon Thau Loo", days:"TR", start:"13:30", end:"15:00", capacity:200, enrolled:[] },
  "CIS550": { id:"CIS550", name:"Database and Information Systems", lecturer:"Mayur H Naik", days:"MW", start:"10:30", end:"12:00", capacity:200, enrolled:[] },
  "CIS553": { id:"CIS553", name:"Networked Systems", lecturer:"Vincent F Liu", days:"MW", start:"16:30", end:"18:00", capacity:150, enrolled:[] },
  "CIS555": { id:"CIS555", name:"Internet and Web Systems", lecturer:"Zachary Ives", days:"MW", start:"12:00", end:"13:30", capacity:100, enrolled:[] },
  "CIS557": { id:"CIS557", name:"Programming for the Web", lecturer:"Eric Noel Fouh Mbindi", days:"MW", start:"13:30", end:"15:00", capacity:40, enrolled:[] },
  "CIS559": { id:"CIS559", name:"Programming and Problem Solving", lecturer:"Swapneel Sheth", days:"MW", start:"15:00", end:"16:30", capacity:25, enrolled:[] },
  "CIS560": { id:"CIS560", name:"Interactive Computer Graphics", lecturer:"Adam D Mally", days:"MW", start:"12:00", end:"13:30", capacity:80, enrolled:[] },
  "CIS561": { id:"CIS561", name:"Advanced Rendering", lecturer:"Adam D Mally", days:"MW", start:"13:30", end:"15:00", capacity:50, enrolled:[] },
  "CIS568": { id:"CIS568", name:"Game Design Practicum", lecturer:"Stephen Lane", days:"MW", start:"15:00", end:"16:30", capacity:25, enrolled:[] },
  "CIS571": { id:"CIS571", name:"Computer Organization and Design", lecturer:"Joseph L Devietti", days:"TR", start:"12:00", end:"13:30", capacity:170, enrolled:[] },
  "CIS580": { id:"CIS580", name:"Machine Perception", lecturer:"Konstantinos Daniilidis", days:"MW", start:"12:00", end:"13:30", capacity:100, enrolled:[] },
  "CIS620": { id:"CIS620", name:"Advanced Topics in Machine Learning", lecturer:"Dan Roth", days:"M", start:"15:00", end:"18:00", capacity:40, enrolled:[] },
  "CIS660": { id:"CIS660", name:"Advanced Topics in Computer Graphics and Animation", lecturer:"Stephen Lane", days:"MW", start:"10:30", end:"12:00", capacity:32, enrolled:[] },
  "CIS670": { id:"CIS670", name:"Advanced Topics in Programming Languages", lecturer:"Stephan A. Zdancewic", days:"MW", start:"13:00", end:"15:00", capacity:32, enrolled:[] }
};


import { courses } from "./data.js";

Object.values(courses).forEach(course => {
  const prof = professors.find(p => p.name === course.lecturer);
  if (prof) prof.assigned.push(course.id);
});
